# Copyright (C) 2022  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM alpine:3.15
MAINTAINER Christian Berger "christian.berger@gu.se"
RUN apk update && \
    apk --no-cache add \
        perl \
        imagemagick \
        imagemagick-perlmagick \
        perl-libwww
 
RUN cd /usr/bin && wget https://raw.githubusercontent.com/chrberger/gpx2png/master/gpx2png.pl
WORKDIR /tmp
ENTRYPOINT ["/usr/bin/perl","/usr/bin/gpx2png.pl"]

